name: E2E Test

on:
  push:
    branches:
      - trunk
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build: 
    uses: 10up/simple-podcasting/.github/workflows/build-release-zip.yml@update/207 # TODO: Update this to develop branch.
  cypress:
    needs: build
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        core:
          - {name: 'WP latest', version: 'latest'}
          - {name: 'WP trunk', version: 'WordPress/WordPress#master'}
          - {name: 'WP minimum', version: 'WordPress/WordPress#5.7'}

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Download build zip
      uses: actions/download-artifact@v3
      with:
        name: ${{ github.event.repository.name }}
        path: ${{ github.event.repository.name }}
    - name: Display structure of downloaded files
      run: ls -R
      working-directory: ${{ github.event.repository.name }}
    - name: Cache node_modules
      id: cache-node-modules
      uses: actions/cache@v3
      env:
        cache-name: cache-node-modules
      with:
        path: |
          node_modules
          ~/.cache
          ~/.npm
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
    - name: Install dependencies
      run: npm install
    - name: Set the core version and plugins config 
      run: ./tests/bin/set-wp-config.js --core=${{ matrix.core.version }} --plugins=./${{ github.event.repository.name }}

    - name: Set up WP environment
      run: npm run wp-env start
      continue-on-error: ${{ matrix.core.name == 'WP trunk' }}

    - name: Test
      run: npm run cypress:run
      continue-on-error: ${{ matrix.core.name == 'WP trunk' }}

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      if: failure()
      with:
        name: cypress-artifact
        retention-days: 2
        path: |
          ${{ github.workspace }}/tests/cypress/screenshots/
          ${{ github.workspace }}/tests/cypress/videos/
          ${{ github.workspace }}/tests/cypress/logs/
